package model;

/**
 * Class representing a machine object.
 * 
 * saleDay: immutable object representing the day on which the machine is for
 * sale.
 * 
 * salePrice: immutable object representing the dollar price for which the
 * machine may be bought.
 *
 * resalePrice: immutable object representing the dollar price for which it may
 * be resold.
 * 
 * profit: immutable object representing the daily profit generated by operating
 * the machine.
 */
public class Machine {

	// Di, Pi, Ri and Gi
	private int saleDay;
	private int salePrice;
	private int resalePrice;
	private int profit;

	public Machine(int saleDay, int salePrice, int resalePrice, int profit) {

		this.saleDay = saleDay;
		this.salePrice = salePrice;
		this.resalePrice = resalePrice;
		this.profit = profit;
	}

	public int getSaleDay() {
		return saleDay;
	}

	public int getSalePrice() {
		return salePrice;
	}

	public int getResalePrice() {
		return resalePrice;
	}

	public int getProfit() {
		return profit;
	}

	@Override
	public String toString() {
		return saleDay + "-" + salePrice + "-" + resalePrice + "-" + profit;
	}

}
